#!/bin/bash
# webapiner daemon
# chkconfig: 345 20 80
# description: myapp daemon
# processname: myapp

DAEMON_PATH="/home/casey/workspace/webapiner2/src/"

NAME=webapiner
DESC="Webapiner init.d script."
PIDFILE=/home/casey/workspace/webapiner2/src/$NAME.pid
SCRIPTNAME=/home/casey/workspace/webapiner2/$NAME

case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
	screen -dmS webapiner sh run.sh
	sleep 2
	cd ..
    PID=$(cat $PIDFILE)
    if [ -z $PID ]; then
        printf "%s\n" "Failed!"
    else
      
        printf "%s\n" "Done!"
	    printf "%s %s %s %s\n" "PID:" $PID "saved to" $PIDFILE
    fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ ! -d "/proc/"$PID ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running."
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            kill -SIGINT $PID
            for n in {1..10}
			do
			    if [ -d "/proc/"$PID ]; then
                	sleep 1
	            else
	                break
	            fi
			done
			if [ -d "/proc/"$PID ]; then
                	printf "%s\n" "Failed!"
                	printf "%s %s\n" "Try manual kill process with PID: " $PID
	        else
	                printf "%s\n" "Done!"
                        rm -f $PIDFILE

	        fi
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
